### ISSUE TITLE
Suggestion: Loosen restriction on RHS of bind-this operator to allow dotted names

### ISSUE THREAD

**Issue by rbuckton** [js-choi/proposal-bind-this#14]
The current explainer expects the RHS of `::` to be either:
- an Identifier
- a ParenthesizedExpression

This works well for existing variables like this:
```js
import { fn } from "foo";
obj::fn
```

But seems to require excess ceremony when used with module namespace imports:

```js
import * as foo from "foo";
obj::foo.fn // syntax error
obj::(foo.fn) // ok
```

It would be nice to support a dotted name, especially since there are some methods built into the JS core API that intentionally support tear-offs (i.e., Array.prototype.*):

```js
obj::Array.prototype.map
obj::Array.prototype.filter
```

**Comment by ljharb** [comment]
I think the latter example is pretty compelling; i don't find any value in supporting it for module namespace objects (but obv it wouldn't make any sense to treat one differently than the other).

**Comment by js-choi** [comment]
I think this grammar unambiguously fulfills what we want. I will file a pull request later.


```
MemberExpression :
  MemberExpression `[` Expression `]`
  MemberExpression `.` IdentifierName
  MemberExpression TemplateLiteral
  SuperProperty
  MetaProperty
  `new` MemberExpression Arguments
  MemberExpression `.` PrivateIdentifier

SimpleMemberExpression :
  IdentifierReference
  SimpleMemberExpression `.` IdentifierName
  `(` Expression `)`

NewExpression :
  MemberExpression
  `new` NewExpression

BindThisExpression :
  MemberExpression `::` SimpleMemberExpression
  MemberExpression `::` TemplateLiteral
  BindThisExpression `::` SimpleMemberExpression
  BindThisExpression `::` TemplateLiteral

CallExpression :
  CoverCallExpressionAndAsyncArrowHead
  SuperCall
  ImportCall
  CallExpression Arguments
  CallExpression `[` Expression `]`
  CallExpression `.` IdentifierName
  CallExpression TemplateLiteral
  CallExpression `.` PrivateIdentifier
  CallExpression `::` SimpleMemberExpression
  CallExpression `::` TemplateLiteral

OptionalExpression :
  MemberExpression OptionalChain
  BindThisExpression OptionalChain
  CallExpression OptionalChain
  OptionalExpression OptionalChain

OptionalChain :
  `?.` Arguments
  `?.` [ Expression ]
  `?.` IdentifierName
  `?.` TemplateLiteral
  `?.` PrivateIdentifier
  OptionalChain Arguments
  OptionalChain `[` Expression `]`
  OptionalChain `.` IdentifierName
  OptionalChain TemplateLiteral
  OptionalChain `.` PrivateIdentifier
  OptionalChain `::` SimpleMemberExpression
  OptionalChain `::` TemplateLiteral

LeftHandSideExpression :
  NewExpression
  BindThisExpression
  CallExpression
  OptionalExpression

CallMemberExpression :
  MemberExpression Arguments
```

<details>

<summary>Examples</summary>

* LeftHandSideExpression `a.b::c.d`
    * BindThisExpression `a.b::c.d`
        * MemberExpression `a.b`
        * SimpleMemberExpression `c.d`
* LeftHandSideExpression `a.b::c.d()`
    * CallExpression `a.b::c.d()`
        * CallExpression `a.b::c.d`
            * MemberExpression `a.b`
            * SimpleMemberExpression `c.d`
        * Arguments `()`
* LeftHandSideExpression `new a.b::c`
    * NewExpression `new a.b::c`
        * MemberExpression `a.b::c`
             * *SyntaxError*
* LeftHandSideExpression `new a.b::c()`
    * MemberExpression `new a.b::c()`
        * MemberExpression `a.b::c`
             * *SyntaxError*
        * Arguments `()`
* LeftHandSideExpression `new a.b()::c`
    * BindThisExpression `new a.b()::c`
        * MemberExpression `new a.b()`
            * MemberExpression `a.b`
            * Arguments `()`
        * SimpleMemberExpression `c`
* LeftHandSideExpression `a?.b::c.d`
    * OptionalExpression `a?.b::c.d`
        * MemberExpression `a`
        * OptionalChain `?.b::c.d`
            * OptionalChain `?.b`
            * SimpleMemberExpression `c.d`
* LeftHandSideExpression `a.b::c?.d`
    * OptionalExpression `a.b::c?.d`
        * BindThisExpression `a.b::c`
        * OptionalChain `?.d`

</details>

**Comment by js-choi** [comment]
The grammar above parses `a.b::c?.d` as `((a.b)::c)?.d`. 

I don’t like this. It’s surprising when `a.b::c.d` without the `?` groups into `(a.b)::(c.d)`. I think `a.b::c?.d` should be a SyntaxError without parentheses.

I’ll think more about how to make this happen in the formal grammar.
