### ISSUE TITLE
Import Gist that compares with Extensions proposal

### ISSUE THREAD

**Issue by js-choi** [js-choi/proposal-bind-this#9]
I need to integrate [this old Gist that compares this proposal](https://gist.github.com/js-choi/eca7c67f88a2e82c3353fb11e8da46f7) with @hax’s [Stage-1 Extensions proposal](https://github.com/tc39/proposal-extensions). There are a few problems with the Gist, too.

The biggest problem is, as per [the Matrix discussion from two days ago](https://view.matrix.org/room/!wbACpffbfxANskIFZq:matrix.org/?anchor=$aMpjrN6C1cJt2bRH6qBh2mx0bbriPU9Adad4ZxU0sUs&offset=60) and also [discussion in #8](https://github.com/js-choi/proposal-bind-this/issues/8#issuecomment-931758183), the document focuses too much on the security use case.

I’m going to redo this document to focus more on the general frequency of `bind`/`call` and how clunky they currently are.

**Comment by js-choi** [comment]
@acutmore left [a comment on the Gist](https://gist.github.com/js-choi/eca7c67f88a2e82c3353fb11e8da46f7#gistcomment-3914428), to which I’m replying here:

> > // The adversary’s code.
> > delete Set.prototype.slice;
> 
> I think this was supposed to be `delete Set.prototype.has` :)

Yes, the `delete Set.prototype.slice` is a mistake; thanks for catching it! 

> > There is currently no way to harden trusted code against an adversary’s mutation of Function.prototype.call or Function.prototype.bind.
> 
> This is not entirely true. It can be hardened against it just relies on being able to run code before anyone else (just like capturing any global/method before it can be modified).
> 
> ```js
> // at start before other code runs:
> const uncurryThis = Function.bind.bind(Function.call);
>   // f => Function.call.bind(f)
>   // f => (…args) => f.call(…args)
> 
> // or
> const {apply} = Reflect;
> const uncurryThis = f => (that, …args) => apply(f, that, args);
> 
> // then
> const setHas = uncurryThis(Set.prototype.has);
> 
> // later
> setHas(new Set([1]), 1); // true
> ```

It is true that guarding against `Function.prototype.call` mutation is possible with `Function.bind.bind`. This is another old mistake which I’ll need to fix. 

This guard requires wrapping every global method you use in an uncurried-this, à la [@ljharb’s call-bind library](https://www.npmjs.com/package/call-bind), which is transitively used by a ton of websites.
So the argument that I need to make is that (1) this intrinsic call-binding is just one common use case of a very commonly used pair of functions (bind and call), and (2) it is very clunky and requires lots of clunky wrapping.

I do anticipate that the biggest argument against this will be “the method-wrapping is fine; just use the pipe operator if you want a fluent notation”. I am trying to think of ways to respond to that.

**Comment by ljharb** [comment]
to me it’s really not about the postfix part, i just need a way to syntactically change the receiver of a function - it’s just that once that exists, it’s kind of silly to force the awkward ordering of .call when we could easily have natural `o.a(b)` ordering.

**Comment by js-choi** [comment]
> i just need a way to syntactically change the receiver of a function

@ljharb: If the ordering isn’t that important, then people will probably say, “Why do you need syntax to change your function’s receiver? Why not just keep using `Function.call` or your `uncurryThis`/`callBind` wrapper?” It’s already kind of happened in that Matrix conversation, too.

The best argument against that anti-argument that I can think of is developer ergonomics. Using `Function.call`/`uncurryThis`/`callBind` is weird, clunky, and obscuring. `o->fn(a)` or whatever is more ergonomic than `Function.call(fn, o)` because of the ordering resembles `o.fn(a)`. 

If it weren’t for that ergonomic difference, then it’s like what @acutmore said: everything is already possible in userland without syntax. (Possible inherent performance problems with wrapped functions notwithstanding, cf. #8.)

**Comment by ljharb** [comment]
Part of it is robustness, and part of it is ergonomics. We have indisputable evidence that the current state of things is not ergonomic; nobody uses call/bind/apply when an arrow function or unsafe call suffices.
